receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          # allow your app’s origin (or '*' for wide-open dev)
          allowed_origins: ["http://localhost:3000"]

exporters:
  otlphttp/logs:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true
  # See https://github.com/grafana/tempo/blob/main/example/docker-compose/otel-collector/otel-collector.yaml
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [otlphttp/logs]
      # Push to Loki over HTTP
    traces:
      receivers: [otlp]
      exporters: [otlp/tempo]
