# Copyright (c) 2025 by OpenTier GmbH
# SPDX-FileCopyrightText: 2025 OpenTier GmbH
# SPDX-License-Identifier: LGPL-3.0-or-later

# This file is part of OpenTier.

# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 3 of the
# License, or (at your option) any later version.

# This is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with this file.  If not, see <https://www.gnu.org/licenses/>.

services:
  # Override stairs_api to disable authentication for testing
  stairs_api:
    environment:
      - AUTH_ENABLED=true

  # Unified tests service
  unified_tests:
    build:
      context: .
      dockerfile: docker/unified_tests/Dockerfile
    container_name: unified_tests
    environment:
      - STAIRS_API_URL=http://stairs_api:3001
      - DEVICE_GATEWAY_URL=http://device_gateway:8005
      - CI=true
    volumes:
      - ./tests/test-results:/app/test-results
      - ./tests/playwright-report:/app/playwright-report
    networks:
      - private_cloud_network
      - public_cloud_network
    depends_on:
      - device_gateway
      - stairs_api
    # Note: Dependencies are handled by the main docker-compose.yaml
    # Default command is handled by the wait script
