global:
  scrape_interval: 10s

scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets:
          - 'node-exporter:9100'
  # https://github.com/grafana/tempo/blob/main/example/docker-compose/shared/prometheus.yaml
  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3201' ]