{
 "title": "Vehicle Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "device_id",
    "query": {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => exists r.device_id)\n  |> distinct(column: \"device_id\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connectivity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "device_id = \"${device_id}\"\n\nfrom(bucket: \"telemetry\")\n  |> range(start: -120s)\n  |> filter(fn: (r) =>\n    r[\"device_id\"] == device_id and\n    (\n      (r._measurement == \"speed\" and r._field == \"speed\") or\n      (r._measurement == \"battery\" and (r._field == \"battery_level\" or r._field == \"temperature\")) or\n      (r._measurement == \"tires\" and r._field == \"front_tire_pressure\")\n    )\n  )\n  |> aggregateWindow(every: 120s, fn: count, createEmpty: true)\n  |> fill(column: \"_value\", value: 0)\n  |> map(fn: (r) => ({\n    _time: r._time,\n    _value: if r._value > 0 then 1 else 0,\n    _field: \"connectivity\",\n    device_id: r.device_id\n  }))\n  |> yield(name: \"status\")\n"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"battery\")\n  |> filter(fn: (r) => r[\"_field\"] == \"battery_level\")\n  |> filter(fn: (r) => r[\"device_id\"] == \"${device_id}\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Vehicle ${device_id} Location Map",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"location\")\n  |> filter(fn: (r) => r[\"device_id\"] == \"${device_id}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude\" or r[\"_field\"] == \"longitude\")\n  |> group(columns: [\"device_id\", \"_field\"])\n  |> last()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: -50h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"speed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\n  |> filter(fn: (r) => r[\"device_id\"] == \"${device_id}\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Engine temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: -50h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"battery\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"device_id\"] == \"${device_id}\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Engine temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"battery\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"device_id\"] == \"${device_id}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"battery\")\n  |> filter(fn: (r) => r[\"_field\"] == \"battery_level\")\n  |> filter(fn: (r) => r[\"device_id\"] == \"${device_id}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Speed (km/h)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"speed\")\n  |> filter(fn: (r) => r[\"_field\"] == \"speed\")\n  |> filter(fn: (r) => r[\"device_id\"] == \"${device_id}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Tires Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tires\")\n  |> filter(fn: (r) => r[\"_field\"] == \"front_tire_pressure\")\n  |> filter(fn: (r) => r[\"device_id\"] == \"${device_id}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n"
    }
   ]
  }
 ]
}