# Copyright (c) 2025 by OpenTier GmbH
# SPDX-FileCopyrightText: 2025 OpenTier GmbH
# SPDX-License-Identifier: LGPL-3.0-or-later

# This file is part of OpenTier.

# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as
# published by the Free Software Foundation; either version 3 of the
# License, or (at your option) any later version.

# This is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with this file.  If not, see <https://www.gnu.org/licenses/>.

name: Build Validation

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Services
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          [
            "stairs_api",
            "device_gateway",
            "cloud_router",
          ]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_PAT_TOKEN }}
          submodules: recursive

      - name: Build ${{ matrix.service }}
        run: |
          echo "Building ${{ matrix.service }}..."
          if ! docker compose build "${{ matrix.service }}"; then
            echo "::error::Failed to build ${{ matrix.service }}"
            exit 1
          fi
          echo "${{ matrix.service }} built successfully"
