# Copyright (c) 2025 by OpenTier GmbH
# SPDX‑FileCopyrightText: 2025 OpenTier GmbH
# SPDX‑License‑Identifier: MIT

# This file is part of OpenTier.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Code Quality Checks

on:
  pull_request:
    branches: [main]

jobs:
  python-service-check:
    name: Python Service Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          [
            { name: "Device Gateway", path: "cloud/backend/device_gateway" },
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_PAT_TOKEN }}
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install black and flake8
        run: pip install black flake8

      - name: Check formatting with black
        working-directory: ${{ matrix.service.path }}
        run: black --check .

      - name: Run flake8
        working-directory: ${{ matrix.service.path }}
        run: flake8 .

  typescript-service-check:
    name: TypeScript Service Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          [
            {
              name: "STAIRS API",
              path: "cloud/backend/stairs_api",
            },
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_PAT_TOKEN }}
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ${{ matrix.service.path }}
        run: npm ci

      - name: Run Lint
        working-directory: ${{ matrix.service.path }}
        run: npm run lint
