name: API Testing Suite

on:
  pull_request:
    branches: [main]

jobs:
  # Job for API tests only
  api_tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ORG_PAT_TOKEN }}
          submodules: recursive

      - name: Start required backend services for API tests
        run: |
          # Start services in dependency order: cloud_router -> device_gateway -> stairs_api
          # This ensures dependencies are available when each service starts
          
          echo "Starting cloud_router..."
          if ! docker compose -f docker-compose.yaml -f docker-compose.test.yaml up -d --build cloud_router; then
            echo "::error::Failed to start cloud_router"
            exit 1
          fi
          echo "cloud_router started successfully"
          
          echo "Starting device_gateway..."
          if ! docker compose -f docker-compose.yaml -f docker-compose.test.yaml up -d --build device_gateway; then
            echo "::error::Failed to start device_gateway"
            exit 1
          fi
          echo "device_gateway started successfully"
          
          echo "Starting stairs_api..."
          if ! docker compose -f docker-compose.yaml -f docker-compose.test.yaml up -d --build stairs_api; then
            echo "::error::Failed to start stairs_api"
            exit 1
          fi
          echo "stairs_api started successfully"

      - name: Run API tests
        run: |
          # Build unified tests container
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml build unified_tests

          # Run API tests only using the api-tests project
          if ! docker compose -f docker-compose.yaml -f docker-compose.test.yaml run --rm unified_tests /wait-for-services.sh --project api-tests; then
            echo "::error::API tests failed"
            exit 1
          fi

      - name: Upload API test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: |
            tests/test-results
            tests/playwright-report
